# Generated by Django 5.2.13 on 2026-04-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='detail_en',
            field=models.JSONField(blank=True, default=dict, verbose_name='Детали страницы (EN)'),
        ),
        migrations.AddField(
            model_name='service',
            name='full_desc_en',
            field=models.TextField(blank=True, verbose_name='Полное описание (EN)'),
        ),
        migrations.AddField(
            model_name='service',
            name='price_note_en',
            field=models.CharField(blank=True, max_length=120, verbose_name='Примечание к цене (EN)'),
        ),
        migrations.AddField(
            model_name='service',
            name='short_desc_en',
            field=models.TextField(blank=True, verbose_name='Краткое описание (EN)'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название (EN)'),
        ),
    ]
