/**
 * English display names for city/country picker items (storage stays Russian).
 * Keys match strings in `cityOptions.js` CITY_GROUPS.
 */
export const CITY_DISPLAY_EN = {
  Москва: 'Moscow',
  Балашиха: 'Balashikha',
  Подольск: 'Podolsk',
  Мытищи: 'Mytishchi',
  Химки: 'Khimki',
  Люберцы: 'Lyubertsy',
  Королёв: 'Korolyov',
  Красногорск: 'Krasnogorsk',
  Одинцово: 'Odintsovo',
  Домодедово: 'Domodedovo',
  Электросталь: 'Elektrostal',
  Коломна: 'Kolomna',
  Щёлково: 'Shchyolkovo',
  Серпухов: 'Serpukhov',
  Долгопрудный: 'Dolgoprudny',
  Раменское: 'Ramenskoye',
  Реутов: 'Reutov',
  Пушкино: 'Pushkino',
  Жуковский: 'Zhukovsky',
  'Орехово-Зуево': 'Orekhovo-Zuyevo',
  Ногинск: 'Noginsk',
  'Сергиев Посад': 'Sergiyev Posad',
  Видное: 'Vidnoye',
  Лобня: 'Lobnya',
  Клин: 'Klin',
  Дубна: 'Dubna',
  'Наро-Фоминск': 'Naro-Fominsk',
  Чехов: 'Chekhov',
  Дмитров: 'Dmitrov',
  Ступино: 'Stupino',
  'Павловский Посад': 'Pavlovsky Posad',
  Лыткарино: 'Lytkarino',
  Дзержинский: 'Dzerzhinsky',
  Фрязино: 'Fryazino',
  Солнечногорск: 'Solnechnogorsk',
  Ивантеевка: 'Ivanteyevka',
  Воскресенск: 'Voskresensk',
  Котельники: 'Kotelniki',
  Таджикистан: 'Tajikistan',
  Узбекистан: 'Uzbekistan',
  Киргизия: 'Kyrgyzstan',
  Армения: 'Armenia',
  Украина: 'Ukraine',
  Казахстан: 'Kazakhstan',
  Азербайджан: 'Azerbaijan',
  Беларусь: 'Belarus',
  Молдова: 'Moldova',
  Туркменистан: 'Turkmenistan',
  Грузия: 'Georgia',
  Германия: 'Germany',
  Куба: 'Cuba',
  Афганистан: 'Afghanistan',
  Китай: 'China',
  Турция: 'Turkey',
  Индия: 'India',
  Сирия: 'Syria',
  Египет: 'Egypt',
  Латвия: 'Latvia',
  Филиппины: 'Philippines',
  Израиль: 'Israel',
  Иран: 'Iran',
  Бангладеш: 'Bangladesh',
  США: 'United States',
  Нигерия: 'Nigeria',
  Сербия: 'Serbia',
  Франция: 'France',
  Алжир: 'Algeria',
  Вьетнам: 'Vietnam',
  Конго: 'Congo',
  Литва: 'Lithuania',
  Италия: 'Italy',
  Эстония: 'Estonia',
  Камерун: 'Cameroon',
  Великобритания: 'United Kingdom',
  Марокко: 'Morocco',
  Канада: 'Canada',
  Пакистан: 'Pakistan',
  Ангола: 'Angola',
}
