# Generated by Django 5.2.13 on 2026-04-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category_en',
            field=models.CharField(blank=True, max_length=120, verbose_name='Категория (EN)'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_en',
            field=models.TextField(blank=True, verbose_name='Текст (EN)'),
        ),
        migrations.AddField(
            model_name='news',
            name='excerpt_en',
            field=models.TextField(blank=True, verbose_name='Анонс (EN)'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='Заголовок (EN)'),
        ),
    ]
