# Generated by Django 5.2.13 on 2026-04-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='service_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Услуга (EN)'),
        ),
        migrations.AddField(
            model_name='review',
            name='text_en',
            field=models.TextField(blank=True, verbose_name='Текст (EN)'),
        ),
    ]
