# Generated by Django 5.2.13 on 2026-04-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='answer_en',
            field=models.TextField(blank=True, verbose_name='Ответ (EN)'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='Вопрос (EN)'),
        ),
        migrations.AddField(
            model_name='faqcategory',
            name='title_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Тема (EN)'),
        ),
    ]
