# Generated by Django 5.2.13 on 2026-04-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricecategory',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название категории (EN)'),
        ),
        migrations.AddField(
            model_name='priceitem',
            name='duration_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Срок (EN)'),
        ),
        migrations.AddField(
            model_name='priceitem',
            name='title_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='Услуга / позиция (EN)'),
        ),
    ]
